"""add MT5 trading account ownership

Revision ID: 3be397041ce9
Revises: 9a994b36a756
Create Date: 2026-09-15 15:45:27.758126
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be397041ce9'
down_revision: Union[str, Sequence[str], None] = '9a994b36a756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mt5_trading_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mt5_login', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_login', 'server', name='uq_mt5_trading_account_login_server'),
    sa.UniqueConstraint('user_id', name='uq_mt5_trading_account_user_id')
    )
    op.create_index(op.f('ix_mt5_trading_accounts_id'), 'mt5_trading_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_mt5_trading_accounts_user_id'), 'mt5_trading_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mt5_trading_accounts_user_id'), table_name='mt5_trading_accounts')
    op.drop_index(op.f('ix_mt5_trading_accounts_id'), table_name='mt5_trading_accounts')
    op.drop_table('mt5_trading_accounts')
    # ### end Alembic commands ###